version: "3.7"

services:

  db:
    restart: always
    image: postgres:12
    env_file:
      - "./flask/.env"
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "9876:5432"
    container_name: db

  flask:
    build: ./flask
    container_name: flask_prod
    restart: always
    expose:
      - 8080
    env_file:
      - "./flask/.env"
    command: uwsgi app.ini

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "9310:80"
